name: Add Date Suffix to Files

on:
  push:
    branches:
      - main  # 可以根据需要修改为你要监听的分支

jobs:
  rename-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 获取最近两次提交的历史，用于比较文件差异

      - name: Get current Beijing time
        id: date
        run: |
          # 安装 tzdata 包以支持时区设置
          sudo apt-get install -y tzdata
          # 设置时区为北京时间
          sudo timedatectl set-timezone Asia/Shanghai
          # 获取当前北京时间并格式化
          echo "datetime=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Rename modified files
        run: |
          # 找出本次提交中 main/js/mylib/ 路径下修改的 js 文件
          modified_files=$(git diff --name-only HEAD^ HEAD -- 'main/js/mylib/*.js')
          for file in $modified_files; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              # 移除 .js 后面的所有内容
              clean_filename=$(echo "$filename" | sed -E 's/\.js.*//')
              name="${clean_filename%.*}"
              extension="${clean_filename##*.}"
              new_filename="${name}&t=${datetime}.js"

              # 重命名文件
              mv "$file" "$(dirname "$file")/$new_filename"

              # 获取以相同开头的文件列表
              files_with_same_prefix=$(ls "$(dirname "$file")"/"$name"&t=*.js 2>/dev/null)
              file_count=$(echo "$files_with_same_prefix" | wc -l)

              # 如果文件数量少于3，复制原始文件
              if [ "$file_count" -lt 3 ]; then
                cp "$(dirname "$file")/$new_filename" "$(dirname "$file")/$name.js"
              else
                # 如果文件数量超过3，删除最旧的文件
                oldest_file=$(ls -t "$(dirname "$file")"/"$name"&t=*.js | tail -1)
                rm "$oldest_file"
              fi
            fi
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatically add date suffix to modified files"
          branch: ${{ github.ref }}
