# add-date-suffix.yml
name: Add Date Suffix to Files

on:
  push:
    branches:
      - main  # 可以根据需要修改为你要监听的分支

jobs:
  rename-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current Beijing time
        id: date
        run: |
          # 安装tzdata包以支持时区设置
          sudo apt-get install -y tzdata
          # 设置时区为北京时间
          sudo timedatectl set-timezone Asia/Shanghai
          # 获取当前北京时间并格式化
          echo "::set-output name=datetime::$(date +'%Y%m%d%H%M')"

      - name: Rename files
        run: |
          for file in $(find ./js -type f -not -path "./.git/*" -not -name "add-date-suffix.yml"); do
            filename=$(basename "$file")
            extension="${filename##*.}"
            name="${filename%.*}"
            
            # 检查文件名中是否已有类似形式的后缀，如果有则移除
            clean_name=$(echo "$name" | sed -E 's/-[0-9]{12}$//')
            
            new_filename="${clean_name}-${{ steps.date.outputs.datetime }}.${extension}"
            mv "$file" "$(dirname "$file")/$new_filename"
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatically add date suffix to files"
          branch: ${{ github.ref }}
