# add-date-suffix.yml
name: Add Date Suffix to Files

on:
  push:
    branches:
      - main  # 可以根据需要修改为你要监听的分支

jobs:
  rename-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current Beijing time
        id: date
        run: |
          # 安装 tzdata 包以支持时区设置
          sudo apt-get install -y tzdata
          # 设置时区为北京时间
          sudo timedatectl set-timezone Asia/Shanghai
          # 获取当前北京时间并格式化
          echo "::set-output name=datetime::$(date +'%Y%m%d%H%M')"

      - name: Rename files
        run: |
          for file in $(find ./js -type f -not -path "./.git/*" -not -name "add-date-suffix.yml"); do
            filename=$(basename "$file")
            # 清除 .js 后面的所有内容
            clean_filename=$(echo "$filename" | sed -E 's/\.js.*/.js/')
            name="${clean_filename%.*}"
            extension="${clean_filename##*.}"
            new_filename="${name}.${extension}?t=${{ steps.date.outputs.datetime }}"
            mv "$file" "$(dirname "$file")/$new_filename"
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatically add date suffix to files"
          branch: ${{ github.ref }}
