name: JS 文件更新工作流

on:
  push:
    paths:
      - 'js/my/*.js'  # 当 js/my 路径下的 JS 文件有提交时触发

jobs:
  update-js-files:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 拷贝原始文件
        run: |
          # 遍历 js/my 路径下所有修改过的 JS 文件
          for file in $(git diff --name-only --diff-filter=M origin/main js/my/*.js); do
            # 获取文件名前缀
            prefix=$(basename "$file" | cut -d'&' -f1)
            # 获取文件扩展名
            ext="${file##*.}"
            # 获取当前北京时间
            current_time=$(date -u -d '+8 hours' +%Y%m%d%H%M)
            # 生成新的文件名，保留原始文件
            new_file="${file%.*}&t=$current_time.$ext"
            # 拷贝原始文件
            cp "$file" "$new_file"
            echo "已拷贝原始文件 $file 到 $new_file"
          done

      - name: 新增重命名文件
        run: |
          # 遍历 js/my 路径下所有修改过的 JS 文件
          for file in $(git diff --name-only --diff-filter=M origin/main js/my/*.js); do
            # 获取文件名前缀
            prefix=$(basename "$file" | cut -d'&' -f1)
            # 获取文件扩展名
            ext="${file##*.}"
            # 获取当前北京时间
            current_time=$(date -u -d '+8 hours' +%Y%m%d%H%M)
            # 生成新的文件名
            new_file="js/my/${prefix}&t=$current_time.$ext"
            # 复制修改后的文件到新文件名
            cp "$file" "$new_file"
            echo "已新增重命名文件 $file 到 $new_file"
          done

      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add js/my/*.js
          git commit -m "更新 JS 文件并保存历史版本"
          git push
