# my-workflow.yml
# 此工作流用于处理当前仓库/js/mylib/路径下的js文件
# 判断js文件的开头的判断方法是,移除文件名的&t=及其之后的所有内容,留下来的内容就是开头.
# 例如mylib&t=202502161348.js的开头就是mylib.
# 每次当前仓库/js/mylib/路径下的以mylib开头的js文件提交修改后,
# 修改删除日期最旧的以mylib开头的js文件.
# 如果在当前路径下遇到其他开头的js文件(例如tmp&t=202502270010.js),也同上操作.

name: Update and Delete Oldest JS Files

# 当js/mylib/路径下的js文件有提交修改时触发工作流
on:
  push:
    paths:
      - 'js/mylib/*.js'

jobs:
  process-js-files:
    # 使用最新的Ubuntu系统作为运行环境
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码到工作区
      - name: Checkout code
        uses: actions/checkout@v3

      # 第二步：处理文件，删除最旧的文件
      - name: Process and Delete Oldest Files
        run: |
          # 遍历js/mylib/路径下的所有js文件
          for file in js/mylib/*.js; do
            # 提取文件名的开头部分，通过移除&t=及其之后的内容
            prefix=$(basename "$file" | sed 's/&t=.*//')
            # 获取以该前缀开头的所有js文件列表
            files_with_prefix=$(ls js/mylib/"$prefix"&t=*.js 2>/dev/null)
            # 统计以该前缀开头的文件数量
            file_count=$(echo "$files_with_prefix" | wc -l)

            # 如果以该前缀开头的文件数量大于1个
            if [ $file_count -gt 1 ]; then
              # 按文件名中的时间戳排序，找出最旧的文件
              oldest_file=$(echo "$files_with_prefix" | sed 's/.*&t=\([0-9]\{12\}\)\.js/\1 &/' | sort -n | head -n 1 | cut -d' ' -f2)
              if [ -n "$oldest_file" ]; then
                # 检查文件权限，确保可以删除
                chmod +w "$oldest_file"
                # 删除最旧的文件
                rm "$oldest_file"
                echo "Deleted oldest file: $oldest_file"
              else
                echo "No oldest file found to delete for prefix: $prefix"
              fi
            fi
          done

      # 第三步：提交并推送更改到仓库
      - name: Commit and Push Changes
        run: |
          # 配置全局的Git用户名和邮箱
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          # 将js/mylib/路径下的所有js文件添加到暂存区
          git add js/mylib/*.js
          # 检查暂存区是否有更改
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            # 提交更改并添加相应的提交信息
            git commit -m "Delete oldest JS files in js/mylib/"
            # 推送更改到远程仓库
            git push
          fi
