name: Manage JS Files

on:
  push:
    paths:
      - 'js/mylib/*.js'  # 仅在路径下的 JS 文件内容被修改时触发

jobs:
  manage-js-files:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 生成北京时间
        id: beijing-time
        run: |
          BEIJING_TIME=$(TZ='Asia/Shanghai' date +'%Y%m%d%H%M')
          echo "time=$BEIJING_TIME" >> $GITHUB_ENV
          echo "当前北京时间：$BEIJING_TIME"

      - name: 拷贝原始文件
        run: |
          echo "检测到的修改文件："
          git diff --name-only HEAD^ HEAD -- 'js/mylib/*.js' | tee /dev/stderr
          for file in $(git diff --name-only HEAD^ HEAD -- 'js/mylib/*.js'); do
            prefix=$(basename "$file" | sed 's/&t=.*//')
            cp "$file" "$file.copy"
            echo "已拷贝 $file 到 $file.copy"
          done

      - name: 创建新的时间戳文件
        run: |
          BEIJING_TIME="${{ env.time }}"
          for file in $(git diff --name-only HEAD^ HEAD -- 'js/mylib/*.js'); do
            prefix=$(basename "$file" | sed 's/&t=.*//')
            extension="${file##*.}"
            new_file="js/mylib/${prefix}&t=${BEIJING_TIME}.${extension}"
            cp "$file" "$new_file"
            echo "创建了新文件: $new_file"
          done

      - name: 控制文件数量
        run: |
          for file in $(git diff --name-only HEAD^ HEAD -- 'js/mylib/*.js'); do
            prefix=$(basename "$file" | sed 's/&t=.*//')
            files=($(ls -t js/mylib/"$prefix"&t=*.js 2>/dev/null))
            while [ ${#files[@]} -gt 3 ]; do
              oldest_file="${files[-1]}"
              rm "$oldest_file"
              echo "删除最旧的文件: $oldest_file"
              unset files[-1]
            done
          done

      - name: 提交并推送更改
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add js/mylib/*.js
          if git diff --staged --quiet; then
            echo "没有需要提交的更改。"
          else
            git commit -m "管理 JS 文件: 拷贝、创建和控制数量"
            git push
          fi
