name: Mylib 文件版本管理

on:
  push:
    paths:
      - 'js/mylib/*.js'

jobs:
  version-js-files:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 获取修改的文件
        id: 修改的文件
        run: |
          修改的文件列表=$(git diff --name-only --diff-filter=AM HEAD^ HEAD | grep 'js/mylib/.*\.js')
          echo "修改的文件列表=$修改的文件列表" >> $GITHUB_OUTPUT

      - name: 创建新版本
        if: steps.修改的文件.outputs.修改的文件列表 != ''
        run: |
          for 文件 in ${{ steps.修改的文件.outputs.修改的文件列表 }}; do
            文件前缀=$(basename "$文件" | sed 's/&t=[^&]*//')
            新时间戳=$(date -u +"%Y%m%d%H%M")
            新文件名="${文件前缀}&t=${新时间戳}.js"
            新文件路径="js/mylib/${新文件名}"
            cp "$文件" "$新文件路径"
          done

      - name: 提交并推送新文件
        if: steps.修改的文件.outputs.修改的文件列表 != ''
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add js/mylib/*.js
          git commit -m "为修改的 mylib JS 文件创建新版本"
          git push    
