name: Mylib 文件版本管理 Update JS Filename Timestamp

on:
  push:
    paths:
      - 'js/my/*.js'  # 当js/my/路径下的js文件有提交修改时触发工作流

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码到工作区

      - name: Generate Beijing Time
        id: beijing-time
        run: |
          # 获取当前北京时间并格式化为YYYYMMddhhmm
          BEIJING_TIME=$(TZ='Asia/Shanghai' date +'%Y%m%d%H%M')
          echo "::set-output name=time::$BEIJING_TIME" 

      - name: Update Filenames
        run: |
          # 获取北京时间
          BEIJING_TIME="${{ steps.beijing-time.outputs.time }}"
          echo "::set-output name=time::$BEIJING_TIME"
          # 遍历js/my/路径下的所有js文件
          for file in js/my/*.js; do
            # 提取文件名开头
            prefix=$(basename "$file" | sed 's/&t=.*//')
            # 统计以该前缀开头的文件数量
            file_count=$(ls js/my/"$prefix"&t=*.js 2>/dev/null | wc -l)
            # 复制原始文件
            cp "$file" "$file.copy"
            echo "Copied $file to $file.copy"

            if [[ $file =~ (.*t=)[0-9]{12}(.*) ]]; then
              # 提取文件名中需要替换的部分
              new_file="${BASH_REMATCH[1]}${BEIJING_TIME}${BASH_REMATCH[2]}"
              # 重命名文件
              mv "$file" "$new_file"
              echo "Renamed $file to $new_file"
            fi
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add js/my/*.js
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update JS filenames with current Beijing time and manage file count"
            git push
          fi
