name: Mylib 文件版本管理 Update JS Filename Timestamp
#按以下要求,写mylib-workflow.yaml,不能使用python:
#每次,当前仓库/js/mylib/路径下的js文件提交修改后,将文件名中的t=...这部分替换为发生修改时的真实北京时间,随后新增一个此文件在源路径下.
#例1:我修改了mylib&t=202502161348.js中的内容,提交修改后,源路径下新增mylib&t=202505010101.js,另外依旧存在修改前的mylib&t=202502161348.js;
#例2:我删除了mylib&t=202502161348.js,提交修改后,源路径下不新增更多文件
#【判断js文件的开头的判断方法是,移除文件名的&t=及其之后的所有内容,留下来的内容就是开头.例如mylib&t=202502161348.js的开头就是mylib.注意要判断修改类型,如果是删除源文件,则不用新增】

on:
  push:
    paths:
      - 'js/my/*.js'  # 当js/my/路径下的js文件有提交修改时触发工作流

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码到工作区

      - name: Generate Beijing Time
        id: beijing-time
        run: |
          # 获取当前北京时间并格式化为YYYYMMddhhmm
          BEIJING_TIME=$(TZ='Asia/Shanghai' date +'%Y%m%d%H%M')
          echo "::set-output name=time::$BEIJING_TIME" 

      - name: Update Filenames
        run: |
          # 获取北京时间
          BEIJING_TIME="${{ steps.beijing-time.outputs.time }}"
          echo "::set-output name=time::$BEIJING_TIME"
          # 遍历js/my/路径下的所有js文件
          for file in js/my/*.js; do
            # 获取文件在本次提交中的状态
            file_status=$(git status --porcelain -- "$file")
            # 如果文件是被删除状态，则跳过本次循环
            if [[ $file_status == D* ]]; then
              continue
            fi
            # 提取文件名开头
            prefix=$(basename "$file" | sed 's/&t=.*//')
            # 统计以该前缀开头的文件数量
            file_count=$(ls js/my/"$prefix"&t=*.js 2>/dev/null | wc -l)
            # 复制原始文件
            cp "$file" "$file.copy"
            echo "Copied $file to $file.copy"

            if [[ $file =~ (.*t=)[0-9]{12}(.*) ]]; then
              # 提取文件名中需要替换的部分
              new_file="${BASH_REMATCH[1]}${BEIJING_TIME}${BASH_REMATCH[2]}"
              # 重命名文件
              mv "$file" "$new_file"
              echo "Renamed $file to $new_file"
            fi
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add js/my/*.js
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update JS filenames with current Beijing time and manage file count"
            git push
          fi
