name: Update JS File Timestamp

# 当 js/mylib/ 路径下的文件有修改时触发
on:
  push:
    paths:
      - 'js/mylib/*.js'

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置北京时间
      - name: Set up timezone
        run: sudo timedatectl set-timezone Asia/Shanghai

      # 获取当前北京时间
      - name: Get current time
        id: current-time
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M')"

      # 查找并处理修改的 JS 文件
      - name: Process modified JS files
        run: |
          # 获取所有修改的 JS 文件
          modified_files=$(git diff --name-only --diff-filter=d HEAD~1 HEAD | grep 'js/mylib/.*\.js')
          for file in $modified_files; do
            # 提取文件名开头部分
            base_name=$(basename "$file" | sed 's/&t=.*//')
            # 构建新的文件名
            new_file="${file%&t=*}&t=${{ steps.current-time.outputs.timestamp }}.js"
            # 复制文件到新的文件名
            cp "$file" "$new_file"
            echo "Created new file: $new_file"
          done

      # 提交并推送修改
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add js/mylib/*.js
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update JS file timestamps"
            git push
          fi    
